--
-- Copyright ©2004-2020 PEREGRINE I.T. Pty Ltd except where explicitly stated otherwise.
-- Fantasy Grounds is Copyright ©2004-2020 SmiteWorks USA LLC.
-- Copyright to other material within this file may be held by other Individuals and/or Entities.
-- Nothing in or from this LUA file in printed, electronic and/or any other form may be used, copied,
--	transmitted or otherwise manipulated in ANY way without the explicit written consent of
--	PEREGRINE I.T. Pty Ltd or, where applicable, any and all other Copyright holders.
-- Please see the accompanying License for full details.
-- All rights reserved.
--
-- Called By: tButLicenseBase in xDORBaseTemplates.xml
--

local sFormatedText = "<h>LICENSE AGREEMENT AND LIMITED WARRANTY (1.5)</h>"
					.."<h>1) Definitions</h>"
					.."<p>a) The following terms and definitions are used throughout this Agreement:</p>"
					.."<list>"
						.."<li>i) &#34;Agreement&#34; shall mean this Software License and any Support Agreement, including any and all attached Schedules.</li>"
						.."<li>ii) &#34;The Author&#34; shall mean PEREGRINE I.T. Pty Ltd and its officers, representitives, affiliates and/or successors.</li>"
						.."<li>iii) The terms &#34;Program&#34;, &#34;Ruleset&#34;, &#34;Extension&#34; and &#34;Module&#34; are used interchangeable within this Agreement and shall mean the product accompanying this Agreement.</li>"
						.."<li>iv) &#34;Software&#34; shall mean the computer program or programs that accompany this product.</li>"
						.."<li>v) &#34;Content&#34; shall mean any and all Information and/or Data produced via using this product or designed to be used in conjunction with this product.</li>"
						.."<li>vi) &#34;Accompanying Materials&#34; shall mean all other electronic content (eg. Manuals, Tutorial Videos, etc) that accompany this product.</li>"
					.."</list>"
					.."<h>2) Application Of Agreement</h>"
					.."<p>a) By installing and/or using the Software or other electronic Accompanying Materials included with this Agreement you accept the terms of this Agreement with The Author.</p>"
					.."<p>b) If you do not agree to the terms of this Agreement you shall promptly stop using the Program, remove the Program from your computer, and permanently erase all copies of the Program and any Content whether produced by you or someone else.</p>"
					.."<p>c) This is the entire Agreement between the parties relating to this product and supersedes any purchase order, communication, advertising or representation concerning the product.</p>"
					.."<p>d) No change or modification of this Agreement will be valid unless it is in writing and is signed by The Author.</p>"
					.."<h>3) Limited Use License</h>"
					.."<p>a) The Author and his suppliers grant you the right to use one copy of the Program for your personal, non-commercial use only.</p>"
					.."<p>b) Those who legally acquired this product may use it for life.</p>"
					.."<p>c) This License, and the restrictions in this Agreement, cover both the Software and the Accompanying Materials of the product, plus any Content.</p>"
					.."<p>d) All rights not expressly granted are reserved by The Author or its suppliers.</p>"
					.."<p>e) This Agreement does not constitute a sale and does not authorise a sale of the Program or anything created thereby.</p>"
					.."<p>f) This product is protected by copyright law and copyright treaties worldwide. You must treat the Program and associated materials and any elements thereof like any other copyrighted material (eg. a book).</p>"
					.."<p>g) This Agreement is governed by the internal substantive laws of the state of New South Wales and/or the Country of Australia (and not by the 1980 United Nations convention on contracts for the international sale of goods, as amended).</p>"
					.."<p>h) In the event you fail to comply with any of the terms or conditions of this Agreement, your rights to use the Program will end, you shall stop using the Program, remove the Program from your computer, and permanently erase all copies of the Program, including any and all Content.</p>"
					.."<p>j) You may be held legally responsible for any copyright infringement that is caused or encouraged by your failure to abide by the terms of this Agreement.</p>"
					.."<h>4) Your Responsibilities</h>"
					.."<p>a) You May:</p>"
					.."<list>"
						.."<li>i) Use this Program and the Accompanying Materials for personal, non-commercial use only.</li>"
						.."<li>ii) Use any and all Content of this Program for personal, non-commercial use only.</li>"
						.."<li>iii) Distribute this Program and Accompanying Materials, in full, including this Agreement, without modifying the Program it any way, provided that you do not charge a fee nor receive any compensation which a reasonably person could interpret as a fee.</li>"
						.."<li>iv) Distribute any and all Content of this Program, provided that you do not charge a fee nor receive any compensation which a reasonably person could interpret as a fee.</li>"
					.."</list>"
					.."<p>b) You May Not:</p>"
					.."<list>"
						.."<li>i) Modify this Program and/or the Accompanying Materials in any way, in full or in part, except for personal, non-commercial use.</li>"
						.."<li>ii) Distribute a modified version of this Program and/or the Accompanying Materials, in full or in part, to anyone else, without the expressed written consent of The Author.</li>"
						.."<li>iii) Distribute any part of this Program and/or the Accompanying Materials, in whole or in part, modified or not, except as specified under Section (4)(a)(iii), without the expressed written consent of The Author.</li>"
						.."<li>iv) Distribute any and all Content of this Program, in whole or in part, modified or not, except as specified under Section (4)(a)(iv), without the expressed written consent of The Author.</li>"
						.."<li>v) Rent, Lease, License or otherwise transfer this Program without the express written consent of The Author except as allowed in Section (4)(a)(iii).</li>"
						.."<li>vi) Reverse engineer, decompile, disassemble or create derivative works of the Software, except for personal, non-commercial use only.</li>"
						.."<li>vii) Publicly perform or publicly display this Program without the express written consent of The Author.</li>"
						.."<li>viii) Use any of the Accompanying Materials for any commercial purposes or any purpose other than for incorporation into Content produced with the Software except as outlined herein.</li>"
					.."</list>"
					.."<h>5) Limited Warranty</h>"
					.."<p>a) The Author warrants to the Original Licensee only, that the Program shall be substantially free from defects in materials and workmanship for ninety (90) days from the date of delivery.</p>"
					.."<p>b) If within 90 days of delivery the media proves to be defective in any way, you may return the media to The Author. Please include a copy of your sales receipt, packaging slip or invoice, along with a brief note of explanation as to why you are returning the Program.</p>"
					.."<p>c) This limited warranty is void if the failure of the Program has resulted from accident, abuse, misapplication or use of the Program with incompatible hardware.</p>"
					.."<p>d) This limited warranty gives you specific legal rights. Depending upon where you live, you may have other rights which vary from state/country to state/country.</p>"
					.."<h>6) Exclusive Remedy</h>"
					.."<p>a) The Original Licensee's exclusive remedy for the breach of this License shall be, at The Author's option, either:</p>"
					.."<list>"
						.."<li>i) The repair or replacement of the Program that does not meet The Author's limited warranty and which is returned to The Author, at your cost, with a copy of your receipt; or</li>"
						.."<li>ii) A refund of the price, if any, which you paid for the Program and Accompanying Materials.</li>"
					.."</list>"
					.."<h>7) No Other Warranties</h>"
					.."<p>a) The Author, its affiliates, and its suppliers, if any, disclaim all warranties with respect to the Program and Accompanying Materials, either expressed or implied, including but not limited to implied warranties of merchantability, non-infringement of third party rights and fitness for a particular purpose.</p>"
					.."<p>b) The Author does not warrant that the operation of the Program will be without defect or error or will satisfy the requirements of your computer system.</p>"
					.."<p>c) The Author warrants only that the Program will perform as described in the user documentation. No other advertising, description or representation, whether made by a dealer, distributor, agent or employee, shall be binding upon The Author or shall change the terms of this warranty.</p>"
					.."<h>8) Limitations On Damages</h>"
					.."<p>a) This Program may contain significant or insignificant program errors, including errors which may cause an operational interruption of your computer system.</p>"
					.."<p>b) The Program is provided &#34;as is&#34; and you assume full responsibility for determining the suitability of the Program on your system and for results obtained.</p>"
					.."<p>c) In no event shall The Author, its affiliates, or its suppliers, if any, be liable for any consequential or incidental damages whatsoever arising out of the use of or inability to use the Program or Program package, even if they have been advised of the possibility of such damages.</p>"
					.."<p>d) You agree to defend and indemnify The Author, its affiliates, or its suppliers, if any, and hold The Author, its affiliates, or its suppliers, if any, harmless from all claims, losses, damages, complaints, or expenses connected with or resulting from your business operations.</p>"
					.."<p>e) The Author, its affiliates, or its suppliers, if any, shall not be responsible or liable for lost profits or revenues, or for damages or costs incurred as a result of loss of time, data or use of the Software, or from any other cause including, without limitation, products liability, contract or tort damages.</p>"
					.."<p>f) The Author, its affiliates', or its suppliers', if any, liability shall not exceed the actual price paid for the License to use the Program.</p>"
					.."<p>g) Because some states/countries do not allow the exclusion or limitation of liability for consequential or incidental damages, the above limitation may not apply to you.</p>"
					.."<h>9) U.S. Government Restricted Rights</h>"
					.."<p>a) The Program and documentation are provided with restricted rights.</p>"
					.."<p>b) Use, duplication or disclosure by the government is subject to restrictions as set forth in subparagraph (c)(1)(ii) of the Rights In Technical Data And Computer Software Clause at DFARS 252.227-7013 (USA) or subparagraphs (c)(1) and (2) of the Commercial Computer Software-Restricted Rights at 48 cfr 52.227-19 (USA), (as applicable).</p>"
					.."<p>c) The contractor/manufacturer is PEREGRINE I.T. Pty Ltd.</p>"
					.."<h>10) Export Restrictions</h>"
					.."<p>a) You may not export or re-export the Software or any underlying information or technology except in full compliance with all Australian and other applicable laws and regulations.</p>"
					.."<h>11) Further Acknowledgements</h>"
					.."<p>a) You understand and acknowledge that:</p>"
					.."<list>"
						.."<li>i) In order to utilise some features of the Program, you may need to purchase additional images, templates or other content.</li>"
						.."<li>ii) The Author may, at its discretion or as required by its agreements with third parties, cease to support the Program.</li>"
						.."<li>iii) Support that The Author may cease to provide may include server access, web site support and the provision of enabling software.</li>"
						.."<li>iv) In the unlikely event this should happen, you agree that any and all monies paid shall be non-refundable.</li>"
					.."</list>"
					.."<h>12) Miscellaneous Provisions</h>"
					.."<p>a) If this Program was acquired outside Australia, then local law may apply.</p>"
					.."<p>b) If you acquired this Software in Canada, you agree to the following: the parties to this License have expressly required that the License be drawn up in the English language/les parties aux presentes ont expressement exige que la presente convention soient redigees en langue anglaise.</p>"
					.."<p>c) This License and your right to use the Program in any manner will terminate automatically if you violate or fail to comply with any part of this Agreement.</p>"
					.."<p>d) Information in this Agreement is subject to change without notice and does not represent a commitment on the part of The Author.</p>"
					.."<h>13) Severability</h>"
					.."<p>a) If any term of this Agreement is held by a court of competent jurisdiction to be invalid or unenforceable, then this Agreement, including all of the remaining terms, will remain in full force and effect as if such invalid or unenforceable term had never been included.</p>"
					.."<h>14) Headings</h>"
					.."<p>a) Headings used in this Agreement are provided for convenience only and shall not be used to construe meaning or intent.</p>"
					.."<h>COPYRIGHT INFORMATION</h>"
					.."<p>This Software is Copyright PEREGRINE I.T. Pty Ltd &#169; 2004-2020 except where explicitly stated otherwise.</p>"
					.."<p>'Purple Die Over Australia' is Copyright PEREGRINE I.T. Pty Ltd &#169; 2004-2020.</p>"
					.."<p>'Fantasy Grounds' is a trademark of SmiteWorks USA, LLC.</p>"
					.."<p>'Fantasy Grounds' is Copyright &#169; 2004-2020 SmiteWorks USA LLC.</p>"
					.."<p>Some Images were provided by: Joe Collins (aka Jiminimonka), Kevin Dosweld (aka Doswelk), Nick Goddard (aka Nickademus), Damian Hupfeld (aka damned), Giorgos Liadis (aka fantasmamore), Craig Polson (aka Dr. Venture), Zeph Ponos (aka Zeus). Jeffery Redding (aka jreddin1), Todd Stern (aka ll00ll00ll00ll) and Chris Ward (aka Madman).</p>"
					.."<p>All Images are used with permission and are are Copyright &#169; 2014-17 their respective creators.</p>"
					.."<p>Copyright to other material within this Software may be held by other Individuals and/or Entities. Nothing in or from this Software in printed, electronic and/or any other form may be used, copied, transmitted or otherwise manipulated in ANY way without the explicit written consent of PEREGRINE I.T. Pty Ltd or, where applicable, any and all other Copyright holders.</p>"
					.."<p>All rights reserved.</p>"
					.."<h>DONATIONS/SUPPORT</h>"
					.."<p>If you like this Software and find it useful, you may like to consider showing your support by making a Donation so that this Software and similar Software can continue to be maintained and developed.</p>"
					.."<p>Donations can be made via PayPal to:</p>"
					.."<list>"
						.."<li>matthew@peregrineit.net</li>"
					.."</list>"
					.."<p>Thankyou.</p>";

function onButtonPress()
	local oWindow = Interface.openWindow("wcHelpWindowWide","");
	if not oWindow then
		return;
	end
	oWindow.ftHelp.setValue(sFormatedText);
end
